// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKYop_ROqTyG5ssbxW5KN_0AJpmtTQxPQ',
    appId: '1:169553709276:web:6f860ee5ff9d87ba528c19',
    messagingSenderId: '169553709276',
    projectId: 'flutter-template-96295',
    authDomain: 'flutter-template-96295.firebaseapp.com',
    storageBucket: 'flutter-template-96295.appspot.com',
    measurementId: 'G-M3N6EYGBFV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7O_4n9c-YpUdYWW88Q_t9UNsAd91tzZE',
    appId: '1:169553709276:android:374693f62fc6704c528c19',
    messagingSenderId: '169553709276',
    projectId: 'flutter-template-96295',
    storageBucket: 'flutter-template-96295.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcv5ZMDtr53uvvP9GKJUcbVk25-3H_4DU',
    appId: '1:169553709276:ios:ce9703760e4d0684528c19',
    messagingSenderId: '169553709276',
    projectId: 'flutter-template-96295',
    storageBucket: 'flutter-template-96295.appspot.com',
    iosBundleId: 'com.example.flutterTemplate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcv5ZMDtr53uvvP9GKJUcbVk25-3H_4DU',
    appId: '1:169553709276:ios:cebca2dddcb3a2d3528c19',
    messagingSenderId: '169553709276',
    projectId: 'flutter-template-96295',
    storageBucket: 'flutter-template-96295.appspot.com',
    iosBundleId: 'com.example.flutterTemplate.RunnerTests',
  );
}
